apiVersion: v1
kind: Namespace
metadata:
  name: wish

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: wish

spec:
  selector:
    matchLabels:
      app: api-server

  template:
    metadata:
      labels:
        app: api-server

    spec:
      containers:
        - name: api-server
          image: wishapi-image

          ports:
            - name: api-server
              containerPort: 3000
              hostPort: 3000

          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu

---
apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: wish

spec:
  selector:
    app: api-server