apiVersion: v1
kind: Namespace
metadata:
  name: wish

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: wish

spec:
  selector:
    matchLabels:
      app: api-server

  template:
    metadata:
      labels:
        app: api-server

    spec:
      initContainers:
        - name: admin
          image: admin-image
          command: [ '/bin/sh' ]
          args:
            - -c
            - >-
              /admin migrate up &&
              /admin migrate seed
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db_user
                  optional: true
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db_password
                  optional: true
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db_host
                  optional: true
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db_name
                  optional: true
            - name: DB_DISABLE_TLS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db_disabletls
                  optional: true
      containers:
        - name: web-server
          image: wishapi-image

          readinessProbe: # readiness probes mark the service available to accept traffic.
            httpGet:
              path: /debug/readiness
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2

          livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
            httpGet:
              path: /debug/liveness
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2

          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MAIL_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: mail_host
                  optional: false
            - name: MAIL_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: mail_port
                  optional: false
            - name: MAIL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: mail_password
                  optional: false
            - name: MAIL_FROM
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: mail_from
                  optional: false
            - name: MAIL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: mail_username
                  optional: false

          ports:
            - name: web-server
              containerPort: 3000
              hostPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: wish

spec:
  selector:
    app: api-server

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: wish