apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: wish

spec:
  strategy:
    type: Recreate
  template:
    spec:
      volumes:
        - name: project
          hostPath:
            path: /project
      containers:
        - name: web-server
          volumeMounts:
            - mountPath: /app
              name: project

