apiVersion: v1
kind: Namespace
metadata:
  name: observe

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: observe

spec:
  selector:
    matchLabels:
      app: zipkin

  template:
    metadata:
      labels:
        app: zipkin

    spec:
      containers:
        - name: zipkin-server
          image: openzipkin/zipkin-slim:3

          ports:
            - name: zipkin-server
              containerPort: 9411
              hostPort: 9411

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: observe

spec:
  selector:
    app: zipkin

  ports:
    - name: zipkin-server
      port: 9411
      targetPort: zipkin-server
